repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
        description: Ensures file ends in a newline
    -   id: trailing-whitespace
        description: Trims extra whitespaces at end of line, except if file is markdown
        args: [--markdown-linebreak-ext=md]
    -   id: check-ast
        description: Checks if valid Python
    -   id: detect-private-key
        description: Checks for private keys
    -   id: check-added-large-files
        description: Looks at file size, max set to 250kb
        args: [--maxkb=250]
    -   id: detect-aws-credentials
        description: check for aws credentials
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3.7
        description: PEP8 Syntax Checker
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
